### ISSUE TITLE
你好  请从黑名单列表中移除鸢尾牙牙Yamia

### ISSUE THREAD

**Issue by zx2289** [2Jelly2/Bilibili-Live-Room-Blacklist#1]
该主播为个人势  并非勒夫旗下主播

**Comment by 2Jelly2** [comment]
您好，之前有明面上个人势但底下吃勒夫资源的案例，请问有什么可以证明这个情况的来源吗？
视频，直播片段，声明，私信内容或者聊天记录都可以。

**Comment by zx2289** [comment]
请问您所需要的证明具体是指什么内容呢？

**Comment by zx2289** [comment]
难道不应该是您需要证据证明主播吃勒夫资源吗？

**Comment by 2Jelly2** [comment]
> 难道不应该是您需要证据证明主播吃勒夫资源吗？

……？
写这份名单的不是我，我不过是搜集了对应的房间号。
谁提出谁举证是当提出的人需要证明自己正确性时的原则，我从一开始就没有所谓的“正确”。
实际上我在所有地方都写明了我无法保证这个名单的准确性，所以请用户自行判断要不要使用这份Optional的名单并为此负责可以吗？从名单上撤下这个路子只是为了在有保证的情况下尽量避免误伤罢了。


> 请问您所需要的证明具体是指什么内容呢？

任何表明自己和勒夫没有关系的语句皆可。
